const UserErrors = Object.freeze({
    EMAIL_NOT_AVAILABLE: "EMAIL_NOT_AVAILABLE",
    IDENTIFICATION_NUMBER_NOT_AVAILABLE: "IDENTIFICATION_NUMBER_NOT_AVAILABLE",
    INVALID_USER_DATA: "INVALID_USER_DATA"
})

module.exports = { UserErrors };